/** @type {import('tailwindcss').Config} */
module.exports = {
  important: true,
  content: ["./**/*.{razor,html}"],
  theme: {
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '1_5xl': '1482px',
      '2xl': '1536px',
      '3xl': '1800px',
    },
    fontFamily: {
      'enable': 'var(--eds-font-family-normal)'
    },
    fontSize: {
      xs: 'calc(var(--eds-font-size-xs, 0.8125) * 1rem) ',
      sm: 'calc(var(--eds-font-size-s, 1) * 1rem) ',
      md_sm: '1.2rem',
      md: 'calc(var(--eds-font-size-m, 1.5) * 1rem)',
      l: 'calc(var(--eds-font-size-l, 2) * 1rem)',
      xl: 'calc(var(--eds-font-size-xl, 2.75) * 1rem)',
      xxl: 'calc(var(--eds-font-size-xxl, 3) * 1rem)',
    },
    fontWeight: {
      light: 'var(--eds-font-weight-light)',
      normal: 'var(--eds-font-weight-normal)',
      strong: 'var(--eds-font-weight-strong)',
      bold: 'var(--eds-font-weight-bold)',
      extraBold: 'var(--eds-font-weight-xbold)',
    },
    colors: {
      'transparent': 'transparent',
      'white': 'var(--eds-color-white)',
      'black': 'var(--eds-color-black)',
      'orange-90': 'var(--eds-color-orange-90)',
      'orange-80': 'var(--eds-color-orange-80)',
      'orange-70': 'var(--eds-color-orange-70)',
      'orange-60': 'var(--eds-color-orange-60)',
      'orange-50': 'var(--eds-color-orange-50)',
      'orange-40': 'var(--eds-color-orange-40)',
      'orange-30': 'var(--eds-color-orange-30)',
      'orange-20': 'var(--eds-color-orange-20)',
      'orange-10': 'var(--eds-color-orange-10)',
      'purple-90': 'var(--eds-color-purple-90)',
      'purple-80': 'var(--eds-color-purple-80)',
      'purple-70': 'var(--eds-color-purple-70)',
      'purple-60': 'var(--eds-color-purple-60)',
      'purple-50': 'var(--eds-color-purple-50)',
      'purple-40': 'var(--eds-color-purple-40)',
      'purple-30': 'var(--eds-color-purple-30)',
      'purple-20': 'var(--eds-color-purple-20)',
      'purple-10': 'var(--eds-color-purple-10)',
      'lime-90': 'var(--eds-color-lime-90)',
      'lime-80': 'var(--eds-color-lime-80)',
      'lime-70': 'var(--eds-color-lime-70)',
      'lime-60': 'var(--eds-color-lime-60)',
      'lime-50': 'var(--eds-color-lime-50)',
      'lime-40': 'var(--eds-color-lime-40)',
      'lime-30': 'var(--eds-color-lime-30)',
      'lime-20': 'var(--eds-color-lime-20)',
      'lime-10': 'var(--eds-color-lime-10)',
      'fuchsia-90': 'var(--eds-color-fuchsia-90)',
      'fuchsia-80': 'var(--eds-color-fuchsia-80)',
      'fuchsia-70': 'var(--eds-color-fuchsia-70)',
      'fuchsia-60': 'var(--eds-color-fuchsia-60)',
      'fuchsia-50': 'var(--eds-color-fuchsia-50)',
      'fuchsia-40': 'var(--eds-color-fuchsia-40)',
      'fuchsia-30': 'var(--eds-color-fuchsia-30)',
      'fuchsia-20': 'var(--eds-color-fuchsia-20)',
      'fuchsia-10': 'var(--eds-color-fuchsia-10)',
      'steel-90': 'var(--eds-color-steel-90)',
      'steel-80': 'var(--eds-color-steel-80)',
      'steel-70': 'var(--eds-color-steel-70)',
      'steel-60': 'var(--eds-color-steel-60)',
      'steel-50': 'var(--eds-color-steel-50)',
      'steel-40': 'var(--eds-color-steel-40)',
      'steel-30': 'var(--eds-color-steel-30)',
      'steel-20': 'var(--eds-color-steel-20)',
      'steel-15': 'var(--eds-color-steel-15)',
      'steel-10': 'var(--eds-color-steel-10)',
      'red-90': 'var(--eds-color-red-90)',
      'red-80': 'var(--eds-color-red-80)',
      'red-70': 'var(--eds-color-red-70)',
      'red-60': 'var(--eds-color-red-60)',
      'red-50': 'var(--eds-color-red-50)',
      'red-40': 'var(--eds-color-red-40)',
      'red-30': 'var(--eds-color-red-30)',
      'red-20': 'var(--eds-color-red-20)',
      'red-10': 'var(--eds-color-red-10)',
      'teal-90': 'var(--eds-color-teal-90)',
      'teal-80': 'var(--eds-color-teal-80)',
      'teal-70': 'var(--eds-color-teal-70)',
      'teal-60': 'var(--eds-color-teal-60)',
      'teal-50': 'var(--eds-color-teal-50)',
      'teal-40': 'var(--eds-color-teal-40)',
      'teal-30': 'var(--eds-color-teal-30)',
      'teal-20': 'var(--eds-color-teal-20)',
      'teal-10': 'var(--eds-color-teal-10)',
      'yellow-90': 'var(--eds-color-yellow-90)',
      'yellow-80': 'var(--eds-color-yellow-80)',
      'yellow-70': 'var(--eds-color-yellow-70)',
      'yellow-60': 'var(--eds-color-yellow-60)',
      'yellow-50': 'var(--eds-color-yellow-50)',
      'yellow-40': 'var(--eds-color-yellow-40)',
      'yellow-30': 'var(--eds-color-yellow-30)',
      'yellow-20': 'var(--eds-color-yellow-20)',
      'yellow-10': 'var(--eds-color-yellow-10)',
      'blue-90': 'var(--eds-color-blue-90)',
      'blue-80': 'var(--eds-color-blue-80)',
      'blue-70': 'var(--eds-color-blue-70)',
      'blue-60': 'var(--eds-color-blue-60)',
      'blue-50': 'var(--eds-color-blue-50)',
      'blue-40': 'var(--eds-color-blue-40)',
      'blue-30': 'var(--eds-color-blue-30)',
      'blue-20': 'var(--eds-color-blue-20)',
      'blue-10': 'var(--eds-color-blue-10)',
      'green-90': 'var(--eds-color-green-90)',
      'green-80': 'var(--eds-color-green-80)',
      'green-70': 'var(--eds-color-green-70)',
      'green-60': 'var(--eds-color-green-60)',
      'green-50': 'var(--eds-color-green-50)',
      'green-40': 'var(--eds-color-green-40)',
      'green-30': 'var(--eds-color-green-30)',
      'green-20': 'var(--eds-color-green-20)',
      'green-10': 'var(--eds-color-green-10)',
      'brand-background-secondary': 'var(--eds-color-steel-10)',
      'brand-background-base': 'var(--eds-color-white)',
      'brand-border-base': 'var(--eds-color-steel-20)',
      'brand-teal-dark': 'var(--eds-color-teal-50)',
      'brand-teal-light': 'var(--eds-color-teal-20)',
      'brand-teal': 'var(--eds-color-teal-30)',
      'brand-yellow-dark': 'var(--eds-color-yellow-30)',
      'brand-yellow-light': 'var(--eds-color-yellow-10)',
      'brand-yellow': 'var(--eds-color-yellow-20)',
      'brand-red-dark': 'var(--eds-color-red-60)',
      'brand-red-light': 'var(--eds-color-red-20)',
      'brand-red': 'var(--eds-color-red-50)',
      'brand-blue-dark': 'var(--eds-color-blue-90)',
      'brand-blue': 'var(--eds-color-blue-80)',
      'brand-blue-light': 'var(--eds-color-blue-60)',
      'brand-green-dark': 'var(--eds-color-green-60)',
      'brand-green': 'var(--eds-color-green-50)',
      'brand-green-light': 'var(--eds-color-green-40)',
      'brand-accent-dark': 'var(--eds-color-blue-90)',
      'brand-accent': 'var(--eds-color-blue-80)',
      'brand-accent-light': 'var(--eds-color-blue-60)',
      'brand-primary-dark': 'var(--eds-color-green-60)',
      'brand-primary': 'var(--eds-color-green-50)',
      'brand-primary-light': 'var(--eds-color-green-40)',
    },
    extend: {
    },
  },
  plugins: [],
}

